### ISSUE TITLE
Documentation TODO List

### ISSUE THREAD

**Issue by crazywhalecc** [crazywhalecc/static-php-cli#160]
Docs repo: https://github.com/crazywhalecc/static-php-cli-docs

## Guide

- [x] Troubleshooting
- [x] Some extensions have alternative features, but they are not mentioned in the documentation
- [x] Embed SAPI #153 
- [x] Add extensions supported but missing in the doc

## Contributing

- [ ] Project structure - License Dumper #159 
- [ ] Project structure - Downloader
- [ ] Project structure - Builder
- [ ] Adding new extensions guide
